# Generated by Django 4.0 on 2021-12-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20)),
                ('profileName', models.CharField(max_length=20)),
                ('helpfulness', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('time', models.TimeField()),
                ('summary', models.CharField(max_length=60)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
