# Generated by Django 4.0 on 2021-12-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productReviewSearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='text',
            new_name='reviewText',
        ),
    ]
